---
name: Publish

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed

jobs: 
  new:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-20.04
    needs: new
    steps:
      - name: echo
        run: echo 'hello world'